apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: logging-storageclass
  labels:
    app: nfs-client-provisioner
provisioner: cluster.local/nfs-client-provisioner
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  archiveOnDelete: "true"

