kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: logging
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>
  containers.input.conf: |-
    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      localtime
      tag raw.kubernetes.*
      format json
      read_from_head true
    </source>
   
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

  forward.input.conf: |-
    <source>
      @type forward
    </source>

  output.conf: |-
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <match **>
      @id kafka      
      @type kafka2
      @log_level info
      include_tag_key true
      brokers kfk-kafka-headless:9092
      zookeeper kfk-zookeeper-headless:2181
      use_event_time true
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
      <format>
        @type json
      </format>
      topic_key k8s_log
      defult_topic k8s_log
      required_acks -1
      compression_codec gzip
    </match>  
